---

- name:
  hosts: run
  tasks:
    - name: deploy code
      import_role:
         name: install_docker
      tags: always
    - name: run proxy
      import_role:
         name: config_nginx
      tags:
        - always
        - proxy
  user: root


